/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerLoaderRouteImport } from './routes/server-loader'
import { Route as ServerActionRouteImport } from './routes/server-action'
import { Route as ClientEnvRouteImport } from './routes/client-env'
import { Route as ApiRouteRouteImport } from './routes/api-route'
import { Route as IndexRouteImport } from './routes/index'

const ServerLoaderRoute = ServerLoaderRouteImport.update({
  id: '/server-loader',
  path: '/server-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerActionRoute = ServerActionRouteImport.update({
  id: '/server-action',
  path: '/server-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientEnvRoute = ClientEnvRouteImport.update({
  id: '/client-env',
  path: '/client-env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteRoute = ApiRouteRouteImport.update({
  id: '/api-route',
  path: '/api-route',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-route': typeof ApiRouteRoute
  '/client-env': typeof ClientEnvRoute
  '/server-action': typeof ServerActionRoute
  '/server-loader': typeof ServerLoaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-route': typeof ApiRouteRoute
  '/client-env': typeof ClientEnvRoute
  '/server-action': typeof ServerActionRoute
  '/server-loader': typeof ServerLoaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-route': typeof ApiRouteRoute
  '/client-env': typeof ClientEnvRoute
  '/server-action': typeof ServerActionRoute
  '/server-loader': typeof ServerLoaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-route'
    | '/client-env'
    | '/server-action'
    | '/server-loader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api-route' | '/client-env' | '/server-action' | '/server-loader'
  id:
    | '__root__'
    | '/'
    | '/api-route'
    | '/client-env'
    | '/server-action'
    | '/server-loader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRouteRoute: typeof ApiRouteRoute
  ClientEnvRoute: typeof ClientEnvRoute
  ServerActionRoute: typeof ServerActionRoute
  ServerLoaderRoute: typeof ServerLoaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/server-loader': {
      id: '/server-loader'
      path: '/server-loader'
      fullPath: '/server-loader'
      preLoaderRoute: typeof ServerLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-action': {
      id: '/server-action'
      path: '/server-action'
      fullPath: '/server-action'
      preLoaderRoute: typeof ServerActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-env': {
      id: '/client-env'
      path: '/client-env'
      fullPath: '/client-env'
      preLoaderRoute: typeof ClientEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-route': {
      id: '/api-route'
      path: '/api-route'
      fullPath: '/api-route'
      preLoaderRoute: typeof ApiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRouteRoute: ApiRouteRoute,
  ClientEnvRoute: ClientEnvRoute,
  ServerActionRoute: ServerActionRoute,
  ServerLoaderRoute: ServerLoaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
