import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul>
            <li><a href="/">prerendered</a></li>
            <li><a href="/server">server</a></li>
            <li><a href="/server?leak">server (leak)</a></li>
            <li><a href="/client">client</a></li>
            <li><a href="/client-leak">client (leak)</a></li>
            <li><a href="/action">action</a></li>
            <li><a href="/api-node">API node</a></li>
            <li><a href="/api-node?leak=1">API node (leak)</a></li>
            <li><a href="/api-edge">API edge</a></li>
            <li><a href="/api-edge?leak=1">API edge (leak)</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
